import * as React from 'react';
import { useState, useEffect } from 'react';
import { Box, Typography, Grid, Button, Card, CardContent, CardActions, TextareaAutosize } from '@mui/material';
import EmailIcon from '@mui/icons-material/Email';
import MessageIcon from '@mui/icons-material/Message';
import PhoneIcon from '@mui/icons-material/Phone';
import NoteIcon from '@mui/icons-material/Note';

export default function ContactPage() {
  const whatsappNumber = "+919994419119"; // Your WhatsApp number
  const emailAddress = "godfreykevin070@gmail.com"; // Your email
  const skypeId = "live:.cid.c923c30f23f83a9b"; // Your Skype ID
  const [notes, setNotes] = useState<string>('');

  // Load notes from localStorage on mount
  useEffect(() => {
    const savedNotes = localStorage.getItem('contactNotes');
    if (savedNotes) setNotes(savedNotes);
  }, []);

  const handleEmail = () => {
    const subject = "Contact from CRM";
    const body = encodeURIComponent(
      `Dear  "User",
  
  This is an automated message generated by our CRM system.
  
  Please feel free to reply to this email if you have any questions or concerns.
  
  Best regards,  
  Your CRM Team`
    );
    window.location.href = `mailto:${emailAddress}?subject=${encodeURIComponent(subject)}&body=${body}`;
  };

  const handleMessage = () => {
    window.location.href = `https://wa.me/${whatsappNumber}?text=Hi%20Archana,%20I%27d%20like%20to%20chat%20about%20ALead%20Scoring`;
  };

  const handleCall = () => {
    // Trigger Skype call
    window.location.href = `skype:${skypeId}?call`;
    console.log(`Initiating Skype call to ${skypeId}`);
  };

  const handleNoteChange = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
    setNotes(event.target.value);
  };

  const handleSaveNotes = () => {
    localStorage.setItem('contactNotes', notes);
    alert('Notes saved successfully!');
  };

  return (
    <Box sx={{ padding: 2 }}>
      <Typography variant="h4" gutterBottom>
        Contact Us
      </Typography>
      <Typography variant="subtitle1" gutterBottom>
        Reach out via Email, WhatsApp Message, or Skype Call—and take notes while you’re at it!
      </Typography>

      <Grid container spacing={3} sx={{ mt: 2 }}>
        {/* Email Card */}
        <Grid item xs={12} sm={3}>
          <Card>
            <CardContent>
              <EmailIcon sx={{ fontSize: 40, color: 'primary.main' }} />
              <Typography variant="h6">Email Client</Typography>
              <Typography variant="body2" color="text.secondary">
                {emailAddress}
              </Typography>
            </CardContent>
            <CardActions>
              <Button variant="contained" onClick={handleEmail}>
                Send Email
              </Button>
            </CardActions>
          </Card>
        </Grid>

        {/* Message Card */}
        <Grid item xs={12} sm={3}>
          <Card>
            <CardContent>
              <MessageIcon sx={{ fontSize: 40, color: 'primary.main' }} />
              <Typography variant="h6">Message Client</Typography>
              <Typography variant="body2" color="text.secondary">
                WhatsApp Chat
              </Typography>
            </CardContent>
            <CardActions>
              <Button variant="contained" onClick={handleMessage}>
                Send Message
              </Button>
            </CardActions>
          </Card>
        </Grid>

        {/* Call Card */}
        <Grid item xs={12} sm={3}>
          <Card>
            <CardContent>
              <PhoneIcon sx={{ fontSize: 40, color: 'primary.main' }} />
              <Typography variant="h6">Call Us</Typography>
              <Typography variant="body2" color="text.secondary">
                Skype Call to Nimitt
              </Typography>
            </CardContent>
            <CardActions>
              <Button variant="contained" onClick={handleCall}>
                Make a Call
              </Button>
            </CardActions>
          </Card>
        </Grid>

        {/* Notes Card */}
        <Grid item xs={12} sm={3}>
          <Card>
            <CardContent>
              <NoteIcon sx={{ fontSize: 40, color: 'primary.main' }} />
              <Typography variant="h6">Take Notes</Typography>
              <TextareaAutosize
                minRows={3}
                placeholder="Write your notes here..."
                value={notes}
                onChange={handleNoteChange}
                style={{ width: '100%', marginTop: '8px', padding: '8px' }}
              />
            </CardContent>
            <CardActions>
              <Button variant="contained" onClick={handleSaveNotes}>
                Save Notes
              </Button>
            </CardActions>
          </Card>
        </Grid>
      </Grid>
    </Box>
  );
}